name = "nitro-secure-service-staging"
uuid = "cage_429c6f3ba413"
app_uuid = "app_a6f793e80534"
team_uuid = "team_e59a7c8b0849"
debug = false
dockerfile = "./Dockerfile"
api_key_auth = true
trx_logging = true
disable_tls_termination = false
forward_proxy_protocol = false

[egress]
enabled = false

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
