name = "nitro-secure-service"
uuid = "cage_56b510bbadc0"
app_uuid = "app_b81dd8dc1c0d"
team_uuid = "team_e59a7c8b0849"
debug = true
dockerfile = "./Dockerfile"
api_key_auth = false
trx_logging = true
disable_tls_termination = false

[egress]
enabled = true
destinations = ["*"]
ports = ["443"]

[signing]
certPath = "cert.pem"
keyPath = "key.pem"
