name = "nitro-secure-service-dev"
uuid = "cage_49cd44b168a0"
app_uuid = "app_b81dd8dc1c0d"
team_uuid = "team_e59a7c8b0849"
debug = false
dockerfile = "./Dockerfile"
api_key_auth = true
trx_logging = true
disable_tls_termination = false
forward_proxy_protocol = false
trusted_headers = []

[egress]
enabled = true
destinations = ["dev.auth.zelus.io"]

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
