version = 1
name = "nitro-secure-service-prod"
uuid = "cage_828970c9b3b2"
app_uuid = "app_d7c0fe35a2d6"
team_uuid = "team_e59a7c8b0849"
debug = false
dockerfile = "./Dockerfile"
api_key_auth = true
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[egress]
enabled = false

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
