name: Deploy Staging Cage

env:
  TOML_FILE_NAME: 'enclave.staging.toml'
  STAGE: staging

on:
  push:
    paths:
      - .github/workflows/deploy-staging-cage.yml
      - src/**/*
      - cage.staging.toml
      - enclave.staging.toml
      - package*
    branches:
      - staging

jobs:
  deploy-cage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Staging Cage
        env:
          EV_API_KEY: ${{ secrets.STAGING_EVERVAULT_API_KEY }}
          EV_APP_UUID: ${{ secrets.STAGING_EVERVAULT_APP_UUID }}
          EV_CERT: ${{ secrets.STAGING_EVERVAULT_CERT }}
          EV_KEY: ${{ secrets.STAGING_EVERVAULT_KEY }}

        run: |
          sh <(curl https://cli.evervault.com/v4/install -sL)
          echo "$EV_CERT" > cert.pem
          echo "$EV_KEY" > key.pem
          ev enclave deploy -c $TOML_FILE_NAME

      - name: Save PCR Attestations
        uses: actions/upload-artifact@v3
        with:
            name: pcr-attestations
            path: ${{ env.TOML_FILE_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CDK_DEPLOYMENT_AMAZON_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.CDK_DEPLOYMENT_AMAZON_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Upload PCRs to AWSSM
        run: cd scripts && yarn && node upload-pcrs.js $TOML_FILE_NAME nitro-secure-service/$STAGE/pcrs