name: Deploy Prod Cage

env:
  TOML_FILE_NAME: 'enclave.prod.toml'
  STAGE: 'prod'

on:
  push:
    paths:
      - .github/workflows/deploy-prod-cage.yml
      - src/**/*
      - cage.prod.toml
      - enclave.prod.toml
    branches:
      - master

jobs:
  deploy-cage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Prod Cage
        env:
          EV_API_KEY: ${{ secrets.PROD_EVERVAULT_API_KEY }}
          EV_CERT: ${{ secrets.PROD_EVERVAULT_CERT }}
          EV_KEY: ${{ secrets.PROD_EVERVAULT_KEY }}

        run: |
          curl https://enclave-build-assets.evervault.com/cli/v1/1.0.3/install -sL | sh
          echo "$EV_CERT" > cert.pem
          echo "$EV_KEY" > key.pem
          ev-enclave deploy -c $TOML_FILE_NAME

      - name: Save PCR Attestations
        uses: actions/upload-artifact@v3
        with:
            name: pcr-attestations
            path: ${{ env.TOML_FILE_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CDK_DEPLOYMENT_AMAZON_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.CDK_DEPLOYMENT_AMAZON_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Upload PCRs to AWSSM
        run: cd scripts && yarn && node upload-pcrs.js $TOML_FILE_NAME nitro-secure-service/$STAGE/pcrs