name: Deploy Dev (Insecure) Cage for Testing

env:
  TOML_FILE_NAME: 'cage.dev-insecure.toml'
  STAGE: dev-insecure

on:
  push:
    paths:
      - .github/workflows/deploy-dev-insecure-cage.yml
      - src/**/*
      - cage.dev-insecure.toml
    branches:
      - develop

jobs:
  deploy-cage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Dev Cage
        env:
          EV_API_KEY: ${{ secrets.DEV_EVERVAULT_API_KEY }}
          EV_CERT: ${{ secrets.DEV_EVERVAULT_CERT }}
          EV_KEY: ${{ secrets.DEV_EVERVAULT_KEY }}

        run: |
          sh <(curl https://cage-build-assets.evervault.com/cli/install -sL)
          echo "$EV_CERT" > cert.pem
          echo "$EV_KEY" > key.pem
          ev-cage deploy -c $TOML_FILE_NAME

      - name: Save PCR Attestations
        uses: actions/upload-artifact@v3
        with:
            name: pcr-attestations
            path: ${{ env.TOML_FILE_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CDK_DEPLOYMENT_AMAZON_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.CDK_DEPLOYMENT_AMAZON_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Upload PCRs to AWSSM
        run: yarn add toml fs aws-sdk && node scripts/upload-pcrs.js $TOML_FILE_NAME nitro-secure-service/$STAGE/pcrs