name: Run Test cases
# write an "on" trigger for this github action to run on pull requests for develop, staging, and master branches
on:
  pull_request:
    branches:
      - develop
      - staging
      - master
  workflow_dispatch:

jobs:
  test-source-code:
    name: Test Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CDK_DEPLOYMENT_AMAZON_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.CDK_DEPLOYMENT_AMAZON_SECRET_KEY }}
          aws-region: 'us-east-1'

      - name: Create .npmrc for access to GitHub Packages
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n@zelusio:registry=https://npm.pkg.github.com/" > .npmrc

      - name: Install Dependencies
        id: install-deps
        run: npm install

      - name: Run Tests
        id: run-tests
        env:
          EV_API_KEY: ${{ secrets.DEV_EVERVAULT_API_KEY }}
          EVERVAULT_API_KEY: ${{ secrets.DEV_EVERVAULT_API_KEY }}
          EVERVAULT_APP_ID: ${{ secrets.DEV_EVERVAULT_APP_ID }}
          ENVIRONMENT: test
        run: npm run test

  test-build-dockerfile:
    name: Try Building Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .npmrc for access to GitHub Packages
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n@zelusio:registry=https://npm.pkg.github.com/" > .npmrc

      - name: Build Dockerfile
        env:
          ENVIRONMENT: test
        run: docker build -t nitro-secure-service:test-build -f Dockerfile . --secret id=npmrc,src=.npmrc
